### ISSUE TITLE
Spawn 

### ISSUE THREAD

**Issue by whothat** [gruntjs/grunt-contrib-sass#173]
When trying to use this plugin I receive this message
    `Warning: spawn ENOENT Use --force to continue.`
and then it aborts

I have post on stackoverflow for more info
http://stackoverflow.com/questions/27239945/sass-for-grunt-spawn-enoent-error

thank you

**Comment by zhongdeliu** [comment]
I'm experiencing the kind the same problem, on windows.
What system/os you are on?

After some research I found out, that for me the introduction of "win-spawn" https://github.com/gruntjs/grunt-contrib-sass/commit/35ad9cd45e73bef35b256ebfd8a46506c38439c8
causes the error.
So 0.6.* works, but later versions not... 
As I need the Sass 3.4 sourcemap option, it is kind of a dilemma.

Manually reverting the change/using grunt.util.spawn() solves the issue. However I'm not sure where the actual problem is...

**Comment by whothat** [comment]
I'm using Windows 8.1 
I've been using two consoles, one with the regular sass-watch, and one with the grunt watch and its been working fine. Though it would be nice to use solely grunt.

Can you explain how you're using grunt.until.spawn() to revert?

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/ForbesLindesay/win-spawn/issues

Normal `spawn` caused issues for some users too, so not really an option switching back.
