### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by roine** [gruntjs/grunt-contrib-sass#74]
I'm running grunt sass and I get a file of merely 30 lines compiled in 2s, while it compile in .5s with sass CLI.

here is a piece of code:

```
sass: {
        dev: {
            options: {
                lineNumbers: true
                style: 'expanded'
            }
            files: {
                'app/css/app.css': 'app/sass/app.scss'
            }
        }
    }
```

Here are my tests:

```
$ time sass app/sass/app.scss:app/css/app.css
sass app/sass/app.scss:app/css/app.css  0,57s user 0,04s system 94% cpu 0,650 total

$ grunt sass:dev
Running "sass:dev" (sass) task

Done, without errors.

Elapsed time
sass:dev  2s
Total     2s
```

**Comment by license2e** [comment]
A friend of mine asked me the same question, here are a few possible (maybe?? fingers crossed) things to try to speed it up:

1. Swapping out `grunt-contrib-sass` to `grunt-sass`: https://www.codehive.io/boards/jWAQgK8 
2. Concurrent watches: http://stackoverflow.com/questions/20666237/grunt-with-compass-and-watch-compiles-slow
3. Narrow your sass watch file rules filter, or move to a completely different directory so that it has less files to `watch`

Cheers and Happy New Year 2016 !!!
